fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.0
  hooks:
    - id: check-added-large-files
      args: ["--maxkb=775"]
    - id: check-merge-conflict
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.5.0
  hooks:
    - id: reorder-python-imports
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
    - id: black
- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
      args: ["--config=setup.cfg"]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
        types: [text]
        types_or: [python, rst]
      - id: rst-inline-touching-normal
        types: [text]
        types_or: [python, rst]
-   repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v0.6.1
    hooks:
    - id: sphinx-lint
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    -   id: codespell
        types_or: [python, rst, markdown]
        additional_dependencies: [tomli]
        args: ["--toml", "pyproject.toml"]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: end-of-file-fixer
        exclude: (.txt|^docs/JOSS1|^docs/JOSS2|^examples/data/)
        stages: [commit, merge-commit, push, prepare-commit-msg, commit-msg, post-checkout, post-commit, post-merge, post-rewrite]
    -   id: trailing-whitespace
        stages: [commit, merge-commit, push, prepare-commit-msg, commit-msg, post-checkout, post-commit, post-merge, post-rewrite]
        exclude: (.txt|^docs/JOSS1|^docs/JOSS2|^examples/data/)
