name: Release
on:
  push:
    tags:
      - '**'

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: print-gh-context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  pypi-publish:
    name: Deploy release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mitosis
    permissions:
      id-token: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install Build
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build .
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.11
